const skills = [
  {text: 'aws', image: '/skills/aws.svg', background: '#EFDE57'},
  {text: 'bash', image: '/skills/bash.svg', background: '#72BDA3'},
  {text: 'bootstrap', image: '/skills/bootstrap.svg', background: '#666A86'},
  {text: 'docker', image: '/skills/docker.svg', background: '#05668D'},
  {text: 'express', image: '/skills/express.svg', background: '#F0C987'},
  {text: 'gatsby', image: '/skills/gatsby.svg', background: '#1C6E8C'},
  {text: 'git', image: '/skills/git.svg', background: '#6A7B76'},
  {text: 'github', image: '/skills/github.svg', background: '#22333B'},
  {text: 'graphql', image: '/skills/graphql.svg', background: '#8CABBE'},
  {text: 'heroku', image: '/skills/heroku.svg', background: '#62929E'},
  {text: 'html5', image: '/skills/html5.svg', background: '#939196'},
  {text: 'jest', image: '/skills/jest.svg', background: '#3C787E'},
  {text: 'js', image: '/skills/js.svg', background: '#00A896'},
  {text: 'laravel', image: '/skills/laravel.svg', background: '#005C69'},
  {text: 'nodejs', image: '/skills/nodejs.svg', background: '#3D3B3C'},
  {text: 'php', image: '/skills/php.svg', background: '#D8C99B'},
  {text: 'postgres', image: '/skills/postgres.svg', background: '#A6D49F'},
  {text: 'react', image: '/skills/react.svg', background: '#253D5B'},
  {text: 'redux', image: '/skills/redux.svg', background: '#63A375'},
  {text: 'sass', image: '/skills/sass.svg', background: '#372248'},
  {text: 'sql', image: '/skills/sql.svg', background: '#738290'},
  {text: 'terraform', image: '/skills/terraform.svg', background: '#279AF1'},
  {text: 'ts', image: '/skills/ts.svg', background: '#084B83'},
  {text: 'vscode', image: '/skills/vscode.svg', background: '#23B5D3'},
  {text: 'wordpress', image: '/skills/wordpress.svg', background: '#E1E289'},
];

export default skills;
